---
  extends: "airbnb"
  env:
    browser: true
    es6: true
  plugins: [
    "vue"
  ]
  rules:
    import/extensions: 0
    import/no-unresolved: 0
    no-new: 0
    max-len: [2, 80, 2, { "ignoreUrls": true }]
    quotes: [2, "single"]
  parser:
    babel-eslint
  parserOptions:
    ecmaVersion: 6
